# Generated by Django 4.0.5 on 2022-07-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True)),
                ('content', models.TextField()),
                ('classes', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('click', models.IntegerField()),
            ],
        ),
    ]
